version: '3.8'

services:
  idempotency-api:
    container_name: idempotency_api
    image: node:22
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    ports:
      - "3000:3000"
    networks:
      - idempotency-api-network

  idempotency-api-postgres:
    container_name: idempotency_api_postgres
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: developer
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - idempotency-api-network

  idempotency-api-redis:
    container_name: idempotency_api_redis
    image: redis:7.4.1-alpine
    restart: always
    command: redis-server --requirepass r3d1s
    ports:
      - "6379:6379"
    networks:
      - idempotency-api-network

volumes:
  pgdata:

networks:
  idempotency-api-network: {}
